mysql5.5:
  image: mysql:5.5
  container_name: mysql5.5
  ports:
    - 3355:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./mysql5.5/conf.d:/etc/mysql/conf.d
mysql5.6:
  image: mysql:5.6
  container_name: mysql5.6
  ports:
    - 3356:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./mysql5.6/conf.d:/etc/mysql/conf.d
mysql5.7:
  image: mysql:5.7
  container_name: mysql5.7
  ports:
    - 3357:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./mysql5.5/conf.d:/etc/mysql/conf.d
